### ISSUE TITLE
Compatibility with IntelliJ/ Webstorm 2023.3

### ISSUE THREAD

**Issue by aozora** [KartanHQ/intellij-remix#280]
### Is your feature request related to a problem? Please describe.

Current Version 1.1.27 is not compatible with newest versions 2023.3 of Jetbrains IDEs.
The plugin is disabled with the message: "Not compatible with the version of your running IDE (WebStorm 2023.3)"

**Comment by nekofar** [comment]
I have already solved this issue. Additionally, we will test and implement support for up to 2024.1 in the next release.

https://github.com/KartanHQ/intellij-remix/commit/7562e7a0060b80ffe608e9df889c313887d994d1
